CREATE DATABASE IF NOT EXISTS FORM_HUB;
USE FORM_HUB;

CREATE TABLE IF NOT EXISTS FORMS (
	FORM_ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_TITLE VARCHAR(255) NOT NULL,
    FORM_DESCRIPTION TEXT,
	FORM_ORDER INT DEFAULT 0,
    FORM_STATUS ENUM('ACTIVE','DRAFT') DEFAULT 'DRAFT',
    FORM_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE IF NOT EXISTS FIELDS (
	FIELDS_ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    FIELD_LABEL VARCHAR(255) NOT NULL,
    FIELD_TYPE ENUM('text','number','date','color','select') NOT NULL,
    FIELD_ORDER INT DEFAULT 0,
    FIELD_REQUIRED BOOLEAN DEFAULT FALSE,
	FIELD_SELECT JSON DEFAULT NULL, -- Lưu danh sách mảng cho trường select
    FOREIGN KEY (FORM_ID) REFERENCES FORMS(FORM_ID) ON DELETE CASCADE
); 

CREATE TABLE IF NOT EXISTS SUBMISSIONS (
	SUBMISSION_ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    SUBMISSION_ANSWERS JSON NOT NULL, -- Lưu cặp key-value của các câu trả lời
    SUBMISSION_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FORM_ID) REFERENCES FORMS(FORM_ID) ON DELETE CASCADE
);